### ISSUE TITLE
[Help | General ] CP is not available for all users 

### ISSUE THREAD

**Issue by MurthyAvanithsa** [DavidWeiss2/windows-Credential-Provider-library#2]
The CP is only available for one user all the time, the login options are not being displayed on all users, can anyone please help me understand the issue

**Comment by DavidWeiss2** [comment]
Can you please add references and pictures? it's hard to help if I can't understand what did you expect to get and what you got.

**Comment by bernhardsp** [comment]
Hi, I fixed the problem by adding a CSampleCredential-Array which is filled using the _pCredProviderUserArray->GetAt(i, &pCredUser); call in the CSampleProvider::_EnumerateCredentials() method.
Additionally the GetCredentialCount() method should return the number of created CSampleCredential objects and the GetCredentialAt() method should call QueryInterface() on a CSampleCredential object based on the dwIndex.

**Comment by MurthyAvanithsa** [comment]
> Hi, I fixed the problem by adding a CSampleCredential-Array which is filled using the _pCredProviderUserArray->GetAt(i, &pCredUser); call in the CSampleProvider::_EnumerateCredentials() method.
> Additionally the GetCredentialCount() method should return the number of created CSampleCredential objects and the GetCredentialAt() method should call QueryInterface() on a CSampleCredential object based on the dwIndex.

It worked for me as well, 
if you see the code the GetCredentialAt() was hardcoded to return 1, this has to be dynamic 

@DavidWeiss2 your code helped us a lot in building something productive, thank you

**Comment by DavidWeiss2** [comment]
You are welcome 3> thanks.

**Comment by rublon-jfr** [comment]
> 

Hi, any patches for the upstream? :) Why your change hasnt been marged here yet tho :<
