### ISSUE TITLE
pGina service is not shutting down

### ISSUE THREAD

**Issue by maheshmadhyastha7** [DavidWeiss2/windows-Credential-Provider-library#4]
Hi,
I am facing this when I restart the machine , the windows shows the pgina service is shutting down which will never happen. I have to revert the force stop it. 
Can anyone help pls?
![pgina issue](https://user-images.githubusercontent.com/12908773/74400404-cef29080-4e43-11ea-8f0a-886c5f8031ec.JPG)

**Comment by maheshmadhyastha7** [comment]
I am using pGina fork 3.9.9.12

**Comment by DavidWeiss2** [comment]
Please ask in the pGina project github section:
https://github.com/pgina/pgina
