### ISSUE TITLE
SampleV2CredentialProvider.dll is not being triggered on authentication of user (Win2016)

### ISSUE THREAD

**Issue by mccoyer001** [DavidWeiss2/windows-Credential-Provider-library#6]
I am new to windows app development and just trying to get get the sample running. Using windows 10 sdk 10.0.18362.0. The sample code compiles and the dll is built. Loading the dll with the registry on a Windows 2016 vm and tested a few windows authentication from the console but it does not look like the dll is being triggered. Is it expected that console login would trigger the dll?

**Comment by professormahi** [comment]
Same issue! Did you find any solution?

**Comment by DavidWeiss2** [comment]
Did a tile been created on the login screen?

**Comment by professormahi** [comment]
I've fixed the problem by installing the vcredist_x64 package.

**Comment by ArchieGu** [comment]
@professormahi 
I have installed the vcredist_x64 package, but still got the issue. Could you please give me some help about this?
