### ISSUE TITLE
Addition to list

### ISSUE THREAD

**Issue by rileyg98** [DavidWeiss2/windows-Credential-Provider-library#8]
Hi!

I wrote some random thoughts on writing a credential provider and authentication package, after having dealt with it. I figure these might help if they're added to the list, as I found these the key points I was missing to get things to work. 
https://gist.github.com/rileyg98/228bed3040034be3b03f39aec8dbed72

**Comment by DavidWeiss2** [comment]
@rileyg98 do you want to make a pull request so everyone will see your addition to the project?
